name : Issues
on:
  issues:
    types: [opened, edited, milestoned,closed]
jobs:
    issue :
         runs-on: ubuntu-latest
         steps:
            - name: Print issue Details
              run : echo "${{ toJson(github.event.issue) }}" 
            - name: Print issue Details
              run : echo "${{ toJson(github.event) }}" 
           